// menu-data.js
// Utopia Deli canonical frontend menu data
// Source of truth alignment:
// - Frontend item id = DB item_id
// - Modifier code = DB mod_id
// - Modifier group_id = DB group_id
// - Prices are cents
// - Combo fries are always plain fries

window.MENU = {
  sandwiches: [
    {
      id: "COWBOY",
      item_id: "COWBOY",
      name: "cowboy chikn sandwich",
      price: 1300,
      desc: "Grilled Cowboy Chik'n, Lettuce, Tomato, Ranch, Bac'n.",
      photo: "../images/cowboy_chicken.webp",
      modifiers: {
        sauce: [
          {
            code: "C_SAUCE_BBQ",
            mod_id: "C_SAUCE_BBQ",
            group_id: "COW_SAUCES",
            group_type: "ADD",
            label: "bbq",
            mod_name: "bbq",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "C_SAUCE_BUFFALO",
            mod_id: "C_SAUCE_BUFFALO",
            group_id: "COW_SAUCES",
            group_type: "ADD",
            label: "buffalo",
            mod_name: "buffalo",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "C_SAUCE_GARLICPARM",
            mod_id: "C_SAUCE_GARLICPARM",
            group_id: "COW_SAUCES",
            group_type: "ADD",
            label: "garlic parm",
            mod_name: "garlic parm",
            price: 100,
            price_delta_cents: 100,
          },
          {
            code: "C_SAUCE_JERK",
            mod_id: "C_SAUCE_JERK",
            group_id: "COW_SAUCES",
            group_type: "ADD",
            label: "jerk",
            mod_name: "jerk",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "C_SAUCE_LEMONPEP",
            mod_id: "C_SAUCE_LEMONPEP",
            group_id: "COW_SAUCES",
            group_type: "ADD",
            label: "lemon pepper",
            mod_name: "lemon pepper",
            price: 100,
            price_delta_cents: 100,
          },
          {
            code: "C_SAUCE_TRUTH",
            mod_id: "C_SAUCE_TRUTH",
            group_id: "COW_SAUCES",
            group_type: "ADD",
            label: "truth",
            mod_name: "truth",
            price: 50,
            price_delta_cents: 50,
          },
        ],
        hold: [
          {
            code: "C_HOLD_BACN",
            mod_id: "C_HOLD_BACN",
            group_id: "COW_TAKEOFF",
            group_type: "HOLD",
            label: "no bac'n",
            mod_name: "no bac'n",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_HOLD_CHIVES",
            mod_id: "C_HOLD_CHIVES",
            group_id: "COW_TAKEOFF",
            group_type: "HOLD",
            label: "no chives",
            mod_name: "no chives",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_HOLD_LETTUCE",
            mod_id: "C_HOLD_LETTUCE",
            group_id: "COW_TAKEOFF",
            group_type: "HOLD",
            label: "no lettuce",
            mod_name: "no lettuce",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_HOLD_TOMATO",
            mod_id: "C_HOLD_TOMATO",
            group_id: "COW_TAKEOFF",
            group_type: "HOLD",
            label: "no tomato",
            mod_name: "no tomato",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        noranch: [
          {
            code: "C_NORANCH_FLAG",
            mod_id: "C_NORANCH_FLAG",
            group_id: "COW_NORANCH",
            group_type: "SPECIAL",
            label: "no ranch",
            mod_name: "no ranch",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_SUB_GARLICBUTR",
            mod_id: "C_SUB_GARLICBUTR",
            group_id: "COW_NORANCH",
            group_type: "SPECIAL",
            label: "add garlic butter instead",
            mod_name: "add garlic butter instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_SUB_SAUCE_BBQ",
            mod_id: "C_SUB_SAUCE_BBQ",
            group_id: "COW_NORANCH",
            group_type: "SPECIAL",
            label: "add bbq sauce instead",
            mod_name: "add bbq sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_SUB_SAUCE_BUFF",
            mod_id: "C_SUB_SAUCE_BUFF",
            group_id: "COW_NORANCH",
            group_type: "SPECIAL",
            label: "add buffalo sauce instead",
            mod_name: "add buffalo sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_SUB_SAUCE_JERK",
            mod_id: "C_SUB_SAUCE_JERK",
            group_id: "COW_NORANCH",
            group_type: "SPECIAL",
            label: "add jerk sauce instead",
            mod_name: "add jerk sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "C_SUB_SAUCE_TRTH",
            mod_id: "C_SUB_SAUCE_TRTH",
            group_id: "COW_NORANCH",
            group_type: "SPECIAL",
            label: "add truth sauce instead",
            mod_name: "add truth sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        addons: [
          {
            code: "C_JALAP",
            mod_id: "C_JALAP",
            group_id: "COW_ADDONS",
            group_type: "ADD",
            label: "jalapenos",
            mod_name: "jalapenos",
            price: 100,
            price_delta_cents: 100,
          },
        ],
        combo: [
          {
            code: "C_COMBO_FRIES",
            mod_id: "C_COMBO_FRIES",
            group_id: "COW_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "C_COMBO_SALAD",
            mod_id: "C_COMBO_SALAD",
            group_id: "COW_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
      },
    },

    {
      id: "CLUB",
      item_id: "CLUB",
      name: "chikn club sub",
      price: 1500,
      desc: "Grilled Chik'n Bac'n Cheese on a bed of Lettuce and Tomatoes.",
      photo: "../images/chicken_club.webp",
      modifiers: {
        hold: [
          {
            code: "S_HOLD_BACN",
            mod_id: "S_HOLD_BACN",
            group_id: "CLUB_TAKEOFF",
            group_type: "HOLD",
            label: "no bac'n",
            mod_name: "no bac'n",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_HOLD_CHIVES",
            mod_id: "S_HOLD_CHIVES",
            group_id: "CLUB_TAKEOFF",
            group_type: "HOLD",
            label: "no chives",
            mod_name: "no chives",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_HOLD_LETTUCE",
            mod_id: "S_HOLD_LETTUCE",
            group_id: "CLUB_TAKEOFF",
            group_type: "HOLD",
            label: "no lettuce",
            mod_name: "no lettuce",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_HOLD_TOMATO",
            mod_id: "S_HOLD_TOMATO",
            group_id: "CLUB_TAKEOFF",
            group_type: "HOLD",
            label: "no tomato",
            mod_name: "no tomato",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        noranch: [
          {
            code: "S_NORANCH_FLAG",
            mod_id: "S_NORANCH_FLAG",
            group_id: "CLUB_NORANCH",
            group_type: "SPECIAL",
            label: "no ranch",
            mod_name: "no ranch",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_SUB_GARLICBUTR",
            mod_id: "S_SUB_GARLICBUTR",
            group_id: "CLUB_NORANCH",
            group_type: "SPECIAL",
            label: "add garlic butter instead",
            mod_name: "add garlic butter instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_SUB_SAUCE_BBQ",
            mod_id: "S_SUB_SAUCE_BBQ",
            group_id: "CLUB_NORANCH",
            group_type: "SPECIAL",
            label: "add bbq sauce instead",
            mod_name: "add bbq sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_SUB_SAUCE_BUFF",
            mod_id: "S_SUB_SAUCE_BUFF",
            group_id: "CLUB_NORANCH",
            group_type: "SPECIAL",
            label: "add buffalo sauce instead",
            mod_name: "add buffalo sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_SUB_SAUCE_JERK",
            mod_id: "S_SUB_SAUCE_JERK",
            group_id: "CLUB_NORANCH",
            group_type: "SPECIAL",
            label: "add jerk sauce instead",
            mod_name: "add jerk sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "S_SUB_SAUCE_TRTH",
            mod_id: "S_SUB_SAUCE_TRTH",
            group_id: "CLUB_NORANCH",
            group_type: "SPECIAL",
            label: "add truth sauce instead",
            mod_name: "add truth sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        combo: [
          {
            code: "S_COMBO_FRIES",
            mod_id: "S_COMBO_FRIES",
            group_id: "CLUB_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "S_COMBO_SALAD",
            mod_id: "S_COMBO_SALAD",
            group_id: "CLUB_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
        addons: [
          {
            code: "S_JALAP",
            mod_id: "S_JALAP",
            group_id: "CLUB_ADDONS",
            group_type: "ADD",
            label: "jalapenos",
            mod_name: "jalapenos",
            price: 100,
            price_delta_cents: 100,
          },
        ],
        sauce: [
          {
            code: "S_SAUCE_BBQ",
            mod_id: "S_SAUCE_BBQ",
            group_id: "CLUB_SAUCES",
            group_type: "ADD",
            label: "bbq",
            mod_name: "bbq",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "S_SAUCE_BUFFALO",
            mod_id: "S_SAUCE_BUFFALO",
            group_id: "CLUB_SAUCES",
            group_type: "ADD",
            label: "buffalo",
            mod_name: "buffalo",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "S_SAUCE_GARLICPARM",
            mod_id: "S_SAUCE_GARLICPARM",
            group_id: "CLUB_SAUCES",
            group_type: "ADD",
            label: "garlic parm",
            mod_name: "garlic parm",
            price: 250,
            price_delta_cents: 250,
          },
          {
            code: "S_SAUCE_JERK",
            mod_id: "S_SAUCE_JERK",
            group_id: "CLUB_SAUCES",
            group_type: "ADD",
            label: "jerk",
            mod_name: "jerk",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "S_SAUCE_LEMONPEP",
            mod_id: "S_SAUCE_LEMONPEP",
            group_id: "CLUB_SAUCES",
            group_type: "ADD",
            label: "lemon pepper",
            mod_name: "lemon pepper",
            price: 100,
            price_delta_cents: 100,
          },
          {
            code: "S_SAUCE_TRUTH",
            mod_id: "S_SAUCE_TRUTH",
            group_id: "CLUB_SAUCES",
            group_type: "ADD",
            label: "truth",
            mod_name: "truth",
            price: 50,
            price_delta_cents: 50,
          },
        ],
      },
    },

    {
      id: "FRIED",
      item_id: "FRIED",
      name: "chikn fried chikn sub",
      price: 1300,
      desc: "Crispy Fried Chik'n on a hoagie with lettuce, tomato, ranch.",
      photo: "../images/chicken_fried_chikn_sub.png",
      modifiers: {
        hold: [
          {
            code: "F_NO_BACN",
            mod_id: "F_NO_BACN",
            group_id: "FRIED_TAKEOFF",
            group_type: "HOLD",
            label: "no bac'n",
            mod_name: "no bac'n",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_NO_CHIVES",
            mod_id: "F_NO_CHIVES",
            group_id: "FRIED_TAKEOFF",
            group_type: "HOLD",
            label: "no chives",
            mod_name: "no chives",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_NO_LETTUCE",
            mod_id: "F_NO_LETTUCE",
            group_id: "FRIED_TAKEOFF",
            group_type: "HOLD",
            label: "no lettuce",
            mod_name: "no lettuce",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_NO_TOMATO",
            mod_id: "F_NO_TOMATO",
            group_id: "FRIED_TAKEOFF",
            group_type: "HOLD",
            label: "no tomato",
            mod_name: "no tomato",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        noranch: [
          {
            code: "F_NO_RANCH_FLAG",
            mod_id: "F_NO_RANCH_FLAG",
            group_id: "FRIED_NORANCH",
            group_type: "SPECIAL",
            label: "no ranch",
            mod_name: "no ranch",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_SUB_BBQ",
            mod_id: "F_SUB_BBQ",
            group_id: "FRIED_NORANCH",
            group_type: "SPECIAL",
            label: "add bbq sauce instead",
            mod_name: "add bbq sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_SUB_BUFFALO",
            mod_id: "F_SUB_BUFFALO",
            group_id: "FRIED_NORANCH",
            group_type: "SPECIAL",
            label: "add buffalo sauce instead",
            mod_name: "add buffalo sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_SUB_GARLICBUTR",
            mod_id: "F_SUB_GARLICBUTR",
            group_id: "FRIED_NORANCH",
            group_type: "SPECIAL",
            label: "add garlic butter instead",
            mod_name: "add garlic butter instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_SUB_JERK",
            mod_id: "F_SUB_JERK",
            group_id: "FRIED_NORANCH",
            group_type: "SPECIAL",
            label: "add jerk sauce instead",
            mod_name: "add jerk sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "F_SUB_TRUTH",
            mod_id: "F_SUB_TRUTH",
            group_id: "FRIED_NORANCH",
            group_type: "SPECIAL",
            label: "add truth sauce instead",
            mod_name: "add truth sauce instead",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        combo: [
          {
            code: "F_COMBO_FRIES",
            mod_id: "F_COMBO_FRIES",
            group_id: "FRIED_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "F_COMBO_SALAD",
            mod_id: "F_COMBO_SALAD",
            group_id: "FRIED_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
        addons: [
          {
            code: "F_ADD_JALAP",
            mod_id: "F_ADD_JALAP",
            group_id: "FRIED_ADDONS",
            group_type: "ADD",
            label: "jalapenos",
            mod_name: "jalapenos",
            price: 100,
            price_delta_cents: 100,
          },
        ],
        sauce: [
          {
            code: "F_SAUCE_AIOLI",
            mod_id: "F_SAUCE_AIOLI",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "aioli",
            mod_name: "aioli",
            price: 75,
            price_delta_cents: 75,
          },
          {
            code: "F_SAUCE_BBQ",
            mod_id: "F_SAUCE_BBQ",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "bbq",
            mod_name: "bbq",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "F_SAUCE_BUFFALO",
            mod_id: "F_SAUCE_BUFFALO",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "buffalo",
            mod_name: "buffalo",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "F_SAUCE_GARLICPARM",
            mod_id: "F_SAUCE_GARLICPARM",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "garlic parm",
            mod_name: "garlic parm",
            price: 250,
            price_delta_cents: 250,
          },
          {
            code: "F_SAUCE_JERK",
            mod_id: "F_SAUCE_JERK",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "jerk",
            mod_name: "jerk",
            price: 50,
            price_delta_cents: 50,
          },
          {
            code: "F_SAUCE_LEMONPEP",
            mod_id: "F_SAUCE_LEMONPEP",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "lemon pepper wet",
            mod_name: "lemon pepper wet",
            price: 75,
            price_delta_cents: 75,
          },
          {
            code: "F_SAUCE_TRUTH",
            mod_id: "F_SAUCE_TRUTH",
            group_id: "FRIED_ADDSAUCE",
            group_type: "ADD",
            label: "truth",
            mod_name: "truth",
            price: 50,
            price_delta_cents: 50,
          },
        ],
      },
    },

    {
      id: "PHILLY",
      item_id: "PHILLY",
      name: "philly sub",
      price: 1300,
      desc: ""Stek" OR Chik'n with sautéed onions & bell peppers.",
      photo: "../images/steak_philly.jpg",
      modifiers: {
        protein: [
          {
            code: "P_CHIKN",
            mod_id: "P_CHIKN",
            group_id: "PHILLY_PROTEIN",
            group_type: "REQUIRED",
            label: "chik'n",
            mod_name: "chik'n",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_STEK",
            mod_id: "P_STEK",
            group_id: "PHILLY_PROTEIN",
            group_type: "REQUIRED",
            label: "stek",
            mod_name: "stek",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        addons: [
          {
            code: "P_JALAP",
            mod_id: "P_JALAP",
            group_id: "PHILLY_ADDONS",
            group_type: "ADD",
            label: "jalapeños",
            mod_name: "jalapeños",
            price: 100,
            price_delta_cents: 100,
          },
        ],
        combo: [
          {
            code: "P_COMBO_FRIES",
            mod_id: "P_COMBO_FRIES",
            group_id: "PHILLY_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "P_COMBO_SALAD",
            mod_id: "P_COMBO_SALAD",
            group_id: "PHILLY_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
        hold: [
          {
            code: "P_HOLD_PEPPERS_ONIONS",
            mod_id: "P_HOLD_PEPPERS_ONIONS",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no peppers and onions",
            mod_name: "no peppers and onions",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_NO_AIOLI",
            mod_id: "P_NO_AIOLI",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no aioli",
            mod_name: "no aioli",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_NO_CHEZE",
            mod_id: "P_NO_CHEZE",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no cheze",
            mod_name: "no cheze",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_NO_PARSLEY",
            mod_id: "P_NO_PARSLEY",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no parsley",
            mod_name: "no parsley",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_NO_CHEESE",
            mod_id: "P_NO_CHEESE",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no cheese",
            mod_name: "no cheese",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_NO_ONIONS",
            mod_id: "P_NO_ONIONS",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no onions",
            mod_name: "no onions",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "P_NO_PEPPERS",
            mod_id: "P_NO_PEPPERS",
            group_id: "PHILLY_TAKEOFF",
            group_type: "HOLD",
            label: "no peppers",
            mod_name: "no peppers",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        extras: [
          {
            code: "P_EXTRA_AIOLI",
            mod_id: "P_EXTRA_AIOLI",
            group_id: "PHILLY_EXTRAS",
            group_type: "ADD",
            label: "extra aioli",
            mod_name: "extra aioli",
            price: 75,
            price_delta_cents: 75,
          },
          {
            code: "P_EXTRA_CHEZE",
            mod_id: "P_EXTRA_CHEZE",
            group_id: "PHILLY_EXTRAS",
            group_type: "ADD",
            label: "extra cheze",
            mod_name: "extra cheze",
            price: 100,
            price_delta_cents: 100,
          },
          {
            code: "P_EXTRA_ONIONS",
            mod_id: "P_EXTRA_ONIONS",
            group_id: "PHILLY_EXTRAS",
            group_type: "ADD",
            label: "extra onions",
            mod_name: "extra onions",
            price: 100,
            price_delta_cents: 100,
          },
          {
            code: "P_EXTRA_PEPPERS",
            mod_id: "P_EXTRA_PEPPERS",
            group_id: "PHILLY_EXTRAS",
            group_type: "ADD",
            label: "extra peppers",
            mod_name: "extra peppers",
            price: 100,
            price_delta_cents: 100,
          },
          {
            code: "P_EXTRA_CHIKN",
            mod_id: "P_EXTRA_CHIKN",
            group_id: "PHILLY_EXTRAS",
            group_type: "ADD",
            label: "extra chikn",
            mod_name: "extra chikn",
            price: 200,
            price_delta_cents: 200,
          },
          {
            code: "P_EXTRA_STEK",
            mod_id: "P_EXTRA_STEK",
            group_id: "PHILLY_EXTRAS",
            group_type: "ADD",
            label: "extra stek",
            mod_name: "extra stek",
            price: 200,
            price_delta_cents: 200,
          },
        ],
      },
    },
  ],

  specialties: [
    {
      id: "POPPERS",
      item_id: "POPPERS",
      name: "chikn poppers",
      price: 1000,
      desc: "Crispy chikn dippers or sauced with choice of BBQ, Garlic Parm, Jerk, Buffalo, Lemon Pepper Wet.",
      photo: "../images/chicken_poppers_v3.jpg",
      modifiers: {
        sauce: [
          {
            code: "POP_PLAIN",
            mod_id: "POP_PLAIN",
            group_id: "POP_SAUCE",
            group_type: "ADD",
            label: "plain",
            mod_name: "plain",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "POP_BUFFALO",
            mod_id: "POP_BUFFALO",
            group_id: "POP_SAUCE",
            group_type: "ADD",
            label: "buffalo",
            mod_name: "buffalo",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "POP_GARLIC",
            mod_id: "POP_GARLIC",
            group_id: "POP_SAUCE",
            group_type: "ADD",
            label: "garlic parm",
            mod_name: "garlic parm",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "POP_JERK",
            mod_id: "POP_JERK",
            group_id: "POP_SAUCE",
            group_type: "ADD",
            label: "jerk",
            mod_name: "jerk",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "POP_LEM_WET",
            mod_id: "POP_LEM_WET",
            group_id: "POP_SAUCE",
            group_type: "ADD",
            label: "lemon pepper wet",
            mod_name: "lemon pepper wet",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        combo: [
          {
            code: "POP_COMBO_FRIES",
            mod_id: "POP_COMBO_FRIES",
            group_id: "POP_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "POP_COMBO_SALAD",
            mod_id: "POP_COMBO_SALAD",
            group_id: "POP_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
      },
    },

    {
      id: "DUMPLING_TACOS",
      item_id: "DUMPLING_TACOS",
      name: "korean pork dumpling tacos",
      price: 1000,
      desc: ""Pork", pickled slaw, aioli, and sauce on a dumpling shell. Set of 4 tacos.",
      photo: "../images/korean_pork_dumpling_tacos.jpg",
      modifiers: {
        hold: [
          {
            code: "DUMP_NO_AIOLI",
            mod_id: "DUMP_NO_AIOLI",
            group_id: "DUMPLING_TAKEOFF",
            group_type: "HOLD",
            label: "no aioli",
            mod_name: "no aioli",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "DUMP_NO_JERK",
            mod_id: "DUMP_NO_JERK",
            group_id: "DUMPLING_TAKEOFF",
            group_type: "HOLD",
            label: "no jerk",
            mod_name: "no jerk",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "DUMP_NO_SLAW",
            mod_id: "DUMP_NO_SLAW",
            group_id: "DUMPLING_TAKEOFF",
            group_type: "HOLD",
            label: "no cabbage",
            mod_name: "no cabbage",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        subs: [
          {
            code: "DUMP_SUB_LETTUCE",
            mod_id: "DUMP_SUB_LETTUCE",
            group_id: "DUMPLING_SUBS",
            group_type: "SPECIAL",
            label: "sub lettuce for cabbage",
            mod_name: "sub lettuce for cabbage",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        combo: [
          {
            code: "DUMP_COMBO_FRIES",
            mod_id: "DUMP_COMBO_FRIES",
            group_id: "DUMPLING_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "DUMP_COMBO_SALAD",
            mod_id: "DUMP_COMBO_SALAD",
            group_id: "DUMPLING_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
      },
    },

    {
      id: "ROCKTOWN_SLIDERS",
      item_id: "ROCKTOWN_SLIDERS",
      name: "rocktown bourbon chikn sliders",
      price: 1200,
      desc: "Rocktown distillery bourbon-infused chik'n with fresh slaw and aioli on a garlic butter slider bun.",
      photo: "../images/rocktown_bourbon_slider.jpg",
      modifiers: {
        hold: [
          {
            code: "ROCK_NO_AIOLI",
            mod_id: "ROCK_NO_AIOLI",
            group_id: "ROCK_TAKEOFF",
            group_type: "HOLD",
            label: "no aioli",
            mod_name: "no aioli",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "ROCK_NO_CABBAGE",
            mod_id: "ROCK_NO_CABBAGE",
            group_id: "ROCK_TAKEOFF",
            group_type: "HOLD",
            label: "no cabbage",
            mod_name: "no cabbage",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        combo: [
          {
            code: "R_COMBO_FRIES",
            mod_id: "R_COMBO_FRIES",
            group_id: "ROCK_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "R_COMBO_SALAD",
            mod_id: "R_COMBO_SALAD",
            group_id: "ROCK_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
      },
    },

    {
      id: "BUFFALO_SLIDERS",
      item_id: "BUFFALO_SLIDERS",
      name: "buffalo chik'n sliders",
      price: 1200,
      desc: "Buffalo chik'n sliders with fresh slaw and ranch on a garlic butter slider bun.",
      photo: "../images/buffalo_chikn_slider.jpg",
      modifiers: {
        hold: [
          {
            code: "BUFFALO_NO_RANCH",
            mod_id: "BUFFALO_NO_RANCH",
            group_id: "BUFFALO_TAKEOFF",
            group_type: "HOLD",
            label: "no ranch",
            mod_name: "no ranch",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "BUFFALO_NO_SLAW",
            mod_id: "BUFFALO_NO_SLAW",
            group_id: "BUFFALO_TAKEOFF",
            group_type: "HOLD",
            label: "no slaw",
            mod_name: "no slaw",
            price: 0,
            price_delta_cents: 0,
          },
        ],
        combo: [
          {
            code: "B_COMBO_FRIES",
            mod_id: "B_COMBO_FRIES",
            group_id: "BUFFALO_COMBO",
            group_type: "ADD",
            label: "plain fries",
            mod_name: "plain fries",
            price: 500,
            price_delta_cents: 500,
          },
          {
            code: "B_COMBO_SALAD",
            mod_id: "B_COMBO_SALAD",
            group_id: "BUFFALO_COMBO",
            group_type: "ADD",
            label: "side salad",
            mod_name: "side salad",
            price: 500,
            price_delta_cents: 500,
          },
        ],
      },
    },
  ],

  sides: [
    {
      id: "FRIES",
      item_id: "FRIES",
      name: "fries",
      price: 500,
      desc: "Crinkle-cut fries with a golden, crispy exterior. Choose plain or loaded style.",
      photo: "../images/plain_fries.avif",

      variants: [
        {
          variant_id: "FRIES_PLAIN",
          label: "plain fries",
          variant_name: "plain fries",
          price_delta_cents: 0,
          sell_price_cents: 500,
        },
        {
          variant_id: "FRIES_BACN",
          label: "loaded fries - bac'n",
          variant_name: "loaded fries - bac'n",
          price_delta_cents: 800,
          sell_price_cents: 1300,
        },
        {
          variant_id: "FRIES_CHIKN",
          label: "loaded fries - philly chik'n",
          variant_name: "loaded fries - philly chik'n",
          price_delta_cents: 800,
          sell_price_cents: 1300,
        },
        {
          variant_id: "FRIES_GARLICPARM",
          label: "loaded fries - garlic parm",
          variant_name: "loaded fries - garlic parm",
          price_delta_cents: 800,
          sell_price_cents: 1300,
        },
        {
          variant_id: "FRIES_STEK",
          label: "loaded fries - philly stek",
          variant_name: "loaded fries - philly stek",
          price_delta_cents: 800,
          sell_price_cents: 1300,
        },
      ],

      modifiers: {
        addons: [
          {
            code: "FRIES_ADD_JALAP",
            mod_id: "FRIES_ADD_JALAP",
            group_id: "FRIES_ADDONS",
            group_type: "ADD",
            label: "jalapeños",
            mod_name: "jalapeños",
            price: 100,
            price_delta_cents: 100,
          },
        ],
        extras: [
          {
            code: "FRIES_ADD_BACN",
            mod_id: "FRIES_ADD_BACN",
            group_id: "FRIES_ADDPROTEIN",
            group_type: "ADD",
            label: "add bac'n",
            mod_name: "add bac'n",
            price: 150,
            price_delta_cents: 150,
          },
          {
            code: "FRIES_ADD_CHIKN",
            mod_id: "FRIES_ADD_CHIKN",
            group_id: "FRIES_ADDPROTEIN",
            group_type: "ADD",
            label: "add chik'n",
            mod_name: "add chik'n",
            price: 200,
            price_delta_cents: 200,
          },
          {
            code: "FRIES_ADD_STEK",
            mod_id: "FRIES_ADD_STEK",
            group_id: "FRIES_ADDPROTEIN",
            group_type: "ADD",
            label: "add stek",
            mod_name: "add stek",
            price: 200,
            price_delta_cents: 200,
          },
        ],
      },
    },

    {
      id: "JUICE_CP",
      item_id: "JUICE_CP",
      name: "fresh cold-pressed juice",
      price: 500,
      desc: "Select flavor and size. Current public size is 10 oz plastic bottle.",
      photo: "../images/cold_pressed_juice_v2.jpg",

      variants: [
        {
          variant_id: "JUICE_10OZ",
          label: "10 oz plastic bottle",
          variant_name: "10 oz plastic bottle",
          price_delta_cents: 0,
          sell_price_cents: 500,
        },
      ],

      modifiers: {
        flavor: [
          {
            code: "JFLAV_GREEN",
            mod_id: "JFLAV_GREEN",
            group_id: "JUICE_FLAVOR",
            group_type: "REQUIRED",
            label: "green juice - green apple, cucumber, celery, ginger",
            mod_name: "green juice - green apple, cucumber, celery, ginger",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "JFLAV_ORANGE",
            mod_id: "JFLAV_ORANGE",
            group_id: "JUICE_FLAVOR",
            group_type: "REQUIRED",
            label: "orange machine - orange, carrot, ginger, apple",
            mod_name: "orange machine - orange, carrot, ginger, apple",
            price: 0,
            price_delta_cents: 0,
          },
          {
            code: "JFLAV_SWEET",
            mod_id: "JFLAV_SWEET",
            group_id: "JUICE_FLAVOR",
            group_type: "REQUIRED",
            label: "sweet dreams - strawberry, grapes, watermelon, lemons",
            mod_name: "sweet dreams - strawberry, grapes, watermelon, lemons",
            price: 0,
            price_delta_cents: 0,
          },
        ],
      },
    },

    {
      id: "COOKIES_2",
      item_id: "COOKIES_2",
      name: "two fresh baked chocolate chip cookies",
      price: 400,
      desc: "2 fresh baked chocolate chip cookies.",
      photo: "../images/cookies_v2.jpg",
      modifiers: {},
    },

    {
      id: "SIDE_SALAD",
      item_id: "SIDE_SALAD",
      name: "side salad",
      price: 500,
      desc: "Fresh mixed greens with house vegetables, served with your choice of dressing.",
      photo: "../images/side_salad_v2.png",
      modifiers: {},
    },

    {
      id: "WATER_16OZ",
      item_id: "WATER_16OZ",
      name: "16 oz bottled water",
      price: 200,
      desc: "Crisp, chilled 16 oz bottled water - refreshing and perfect alongside any meal.",
      photo: "../images/bottled_water_v2.png",
      modifiers: {},
    },

    {
      id: "CHIPS_SPIRALS",
      item_id: "CHIPS_SPIRALS",
      name: "potato chip spirals",
      price: 500,
      desc: "Crispy potato chip spirals - seasoned and fried to perfection.",
      photo: "../images/spiral_chips.jpg",
      modifiers: {},
    },
  ],
};
